In [2]:
import numpy as np

In [4]:
np.__version__

'2.3.3'

In [20]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [22]:
a.dtype

dtype('int32')

In [21]:
a.itemsize

4

In [24]:
#get total size
a.size * a.itemsize

12

In [25]:
a.nbytes

12

In [27]:
print(a.itemsize)
print(b.itemsize)

4
8


-----

In [28]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
print(a[1,5])

13
